---
# tasks file for httpd
#
---
 - name: install apache
   yum:
     name: httpd
     state: latest
 - name: copy httpd.conf template
   template:
     src: httpd.conf.j2
     dest: /etc/httpd/conf/httpd.conf
   notify: restart_httpd
 - name:
   service:
     name: httpd
     enabled: yes
     state: started

