---
 - hosts: serverc
   become: true
   tasks: 
    - name: "Instalar {{item}} con items"
      yum:
        name: "{{ item }}"
        state: latest 
      with_items:
       - httpd
       - mariadb-server
    - name: "Levantar {{ item }} con items"
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - httpd
        - mariadb 


       
