---
 - hosts: serverc
   become: true
   tasks: 
    - name: "Instalar apache con items"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
       - httpd
    - name: "levantar apache con items"
      service: 
        name: "{{ item }}"
        state: started
        enabled: true
      with_items: 
       - httpd


       
